---
- name: Create a VM from a template
  vmware_guest:
    hostname: '{{ vcenter }}'
    username: '{{ vsphere_user }}'
    password: '{{ vsphere_password }}'
    validate_certs: no
    name: '{{ item.vm_name }}'
    state: poweredon
    template: '{{ template }}'
    datacenter: '{{ datacenter }}'
    folder: '{{ vm_folder }}'
    cluster: "{{ cluster_name }}"
    disk: "{{ item.disks }}"
    hardware:
      memory_mb: '{{ RAM }}'
      num_cpus: '{{ item.cpu }}'
      scsi: paravirtual
    customization:
      autologon: yes
      dns_servers:
       - 8.8.8.8 
    networks: "{{ item.network }}"
    wait_for_ip_address: yes
  register: deploy
  with_items: 
     - '{{ SRV }}'
...
