---
- name: Create a VM from a template
  vmware_guest:
    vcenter: '10.215.99.55'                         # IP del vCenter donde se crearan las VMs
    vsphere_user: 'administrator@vsphere.local'     # Usuario con privilegios sobre vSphere para creacion de VMs
    vsphere_password: 'Lab2021*'                    # Password de usuario de vSphere con privilegios para creacion de VMs
    validate_certs: no
    name: '{{ item.vm_name }}'
    state: poweredon
    template: '{{ template }}' 
    datacenter: '{{ datacenter }}'
    folder: '{{ vm_folder }}'
    cluster: "{{ cluster_name }}"
    disk:
    - size_gb: '{{ DISK }}'                                       
      type: thin                                            
      datastore: 'Management'
    hardware:
      memory_mb: '{{ RAM }}'
      num_cpus: '{{ CPU }}'
      scsi: paravirtual
    customization:
      autologon: yes
      dns_servers:
       - 8.8.8.8 
    networks:   
    - name: '{{ portgroup_name }}'                                   
      ip: '{{ IP }}'                                              
      netmask: '{{ MASK }}'                                       
      gateway: '{{ GW }}'                                        
      dns_servers:                                               
      - 8.8.8.8
      device_type: vmxnet3                                          
      start_connected: True
    wait_for_ip_address: yes
  register: deploy
  with_items: 
     - '{{ SRV }}'
...
