---
- hosts: all
  connection: local
  tasks:
  - name: snpa
    vmware_guest_snapshot: 
      hostname: 10.215.99.55
      username: administrator@vsphere.local
      password: Lab2021*
      validate_certs: False
      datacenter: CURANSIBLEDCLAB01
      folder: /VMs-Windows/
      name: "{{ item }}"
      state: present
      snapshot_name: snap1
      description: snap1_description
    delegate_to: localhost
  - name: Remove snpa
    vmware_guest_snapshot: 
      hostname: 10.215.99.55
      username: administrator@vsphere.local
      password: Lab2021*
      validate_certs: False
      datacenter: CURANSIBLEDCLAB01
      folder: /VMs-Windows/
      name: "{{ item }}"
      state: absent
      snapshot_name: snap1
      description: snap1_description
    delegate_to: localhost
...
