---
- hosts: all
  tasks:
  - name: Create a snapshot
    community.vmware.vmware_guest_snapshot:
      hostname: 10.215.99.55
      username: administrator@vsphere.local
      password: Lab2021*
      datacenter: CURANSIBLEDCLAB01
      folder: /VMs-Windows/
      name: Windows1
      state: present
      snapshot_name: snap1
      description: snap1_description
    delegate_to: localhost
...
---
- name: add disk
  host: all
  task:
    - vmware_guest_disk:
        hostname: '10.215.99.55'                                         
        username: 'administrator@vsphere.local'
        password: 'Lab2021*'
        validate_certs: False
        datacenter: 'CURANSIBLEDCLAB01'
        name: "{{ target_host }}"
        disk:
          - size_gb: 2
            type: thin
            state: present
            datastore: 'Management'
