  
---
- hosts: all
  connection: local
  tasks:
    - vmware_guest:
        hostname: '{{ vcenter }}'
        username: '{{ vsphere_user }}'
        password: '{{ vsphere_password }}'
        validate_certs: no
        name: '{{ item.vm_name }}'
        state: poweredon
        template: '{{ template }}'
        datacenter: '{{ datacenter }}'
        folder: '{{ vm_folder }}'
        cluster: "{{ cluster_name }}"
        disk: "{{ item.disks }}"
        hardware:
        memory_mb: '{{ item.ram }}'
        num_cpus: '{{ item.cpu }}'
        scsi: paravirtual
        customization:
        autologon: yes
        dns_servers:
         - 8.8.8.8 
#        - 10.129.0.241 
#        - 10.140.1.41 
#      domain: 
        networks: "{{ item.network }}"
        wait_for_ip_address: yes
      register: deploy
      with_items: 
        - '{{ SRV }}'
...
