--- 
- 
  connection: local
  hosts: all
  tasks: 
    - 
      vmware_guest: 
        autologon: true
        cluster: "{{ cluster_name }}"
        customization: ~
        datacenter: "{{ datacenter }}"
        disk: "{{ item.disks }}"
        dns_servers: 
          - "8.8.8.8"
        folder: "{{ vm_folder }}"
        hardware: ~
        hostname: "{{ vcenter }}"
        memory_mb: "{{ item.ram }}"
        name: "{{ item.vm_name }}"
        networks: "{{ item.network }}"
        num_cpus: "{{ item.cpu }}"
        password: "{{ vsphere_password }}"
        scsi: paravirtual
        state: poweredon
        template: "{{ template }}"
        username: "{{ vsphere_user }}"
        validate_certs: false
        #wait_for_ip_address: true
        - 
         cpu: "1"
         name: VM1
         network: 
        - 
          disks: 
            - 
              datastore: "{{ dstore }}"
              size_gb: 20
              type: thin
          gateway: "10.215.99.254"
          ip: "10.215.99.104"
          name: "{{ vm_net }}"
          netmask: "255.255.255.0"
          type: static
      ram: "1024"
      register: deploy
      role: worker-server
      vm_name: CURLABLIX01
      with_items: 
        - "{{ SRV }}"
  vars_files: 
    - Vars.yml
