---
- hosts: all
  connection: local
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3 
  roles:
    - crear_vm_vmware
  vars_files:
    - pruebas_ansible/roles/crear_vm_vmware/vars/vmware.yml
...
