---
- hosts: all
  connection: local
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3 
  roles:
    - Despliege_VariasMV
  vars_files:
    - roles/crear_vm_vmware/vars/vmware_var.yml   
...
