---
- name: add disk
  host: all
  task:
    - vmware_guest_disk:
        hostname: '10.215.99.55'                                         
        username: 'administrator@vsphere.local'
        password: 'Lab2021*'
        validate_certs: False
        datacenter: 'CURANSIBLEDCLAB01'
        name: "{{ target_host }}"
        disk:
          - size_gb: 2
            type: thin
            state: present
            datastore: 'Management'
...