---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - /etc/ansible/crear_vm_vmware
  vars_files:
    - /etc/ansible/crear_vm_vmware/vars/vmware.yml
...
